/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hzlz_tlsgateway */

#ifndef _Included_com_hzlz_tlsgateway
#define _Included_com_hzlz_tlsgateway
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hzlz_tlsgateway
 * Method:    SetAppconfig
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_hzlz_tlsgateway_SetAppconfig
  (JNIEnv *, jclass, jstring, jbyteArray);

/*
 * Class:     com_hzlz_tlsgateway
 * Method:    StartTunnel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hzlz_tlsgateway_StartTunnel
  (JNIEnv *, jclass);

/*
 * Class:     com_hzlz_tlsgateway
 * Method:    StopTunnel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_hzlz_tlsgateway_StopTunnel
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
